# cargo-release configuration
# Usage: cargo release patch/minor/major --execute

allow-branch = ["main"]
sign-commit = false
sign-tag = false
push = true
publish = false
pre-release-hook = ["dist", "generate"]
pre-release-commit-message = "release: v{{version}}"
tag-message = "v{{version}}"
tag-name = "v{{version}}"
consolidate-commits = true
dependent-version = "upgrade"
